apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app.kubernetes.io/name: myingress
spec:
  ingressClassname: nginx
  rules:
  - host: <Host>
    http:
      paths:
      - pathType: Prefix
        path: "/backend"
        backend:
          service:
            name: nginx-service
            port: 
              number: 80
      - pathType: Prefix
        path: "/frontend"
        backend:
          service:
            name: apache-service
            port: 
              number: 80