apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-backend
  template:
    metadata:
      labels:
        app: k8s-backend
    spec:
      containers:
      - name: k8s-backend
        image: saatvik10/k8s-backend
        ports:
        - containerPort: 8080
        # env:
        # - name: PORT
        #   valueFrom:
        #     configMapKeyRef:
        #       name: k8s-backend
        #       key: PORT
        # - name: DATABASE_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: k8s-backend
        #       key: DATABASE_URL
        volumeMounts:
          - name: env-file
            readOnly: true
            mountPath: "/app/secret"
      volumes:
      - name: env-file
        secret:
          secretName: k8s-backend-secret
